### ISSUE TITLE
Build in IANA download feature

### ISSUE THREAD

**Issue by anewton1998** [arineng/rdap_bootstrap_server#1]
Instead of relying on a separate script on the host system to download the IANA files, it would be nice if the software just did this based on a timer.

**Comment by timofonic** [comment]
@anewton1998 I agree. Why has developent of this project stalled?

**Comment by anewton1998** [comment]
Well... there hasn't been much movement on the bootstrap files for many years. That looks to be changing now.

**Comment by gdubin** [comment]
This is now a part of the 2.0.1 release.
