### ISSUE TITLE
[bug] reassigned addresses don't show comments in RDAP

### ISSUE THREAD

**Issue by massimocandela** [arineng/rdap_bootstrap_server#10]
Possibly this is not the right repo for reporting this bug, I hope you can dispatch it to the right place (which I cannot find).

Summary:  reassigned addresses don't have comments in RDAP, even if these can be set in the web UI and work in command-line whois. 

How to reproduce:
* It works on command-line whois
```
whois 64.58.32.0 | grep Comment
Comment:        Geofeed https://as1403.net/geofeed.csv
```

* The same resource will appear without comments in rdap
```
curl -v --silent https://rdap.arin.net/registry/ip/64.58.32.0 2>&1 | grep Geofeed

same for 

curl -v --silent https://rdap.arin.net/registry/ip/64.58.32.0/20 2>&1 | grep Geofeed
```

It looks like this happens with reassigned resources, with other resources it looks fine.
[Here](https://github.com/massimocandela/geofeed-finder/issues/4) you can find where initially this bug was reported, including more examples.

Thanks!

**Comment by gdubin** [comment]
Thank you for reporting this.  This appears to be an issue with the output from RDAP.  Our RDAP server (not bootstrap) is closed source so there's really no publicly available repository to post this report to.  I'll document this in our internal ticketing system, close this issue and leave a note to message you when this has been fixed.

**Comment by massimocandela** [comment]
Any update about this issue? I can still reproduce the bug.
