### ISSUE TITLE
rdap.afilias.net is probably no longer valid

### ISSUE THREAD

**Issue by klkvsk** [arineng/rdap_bootstrap_server#12]
The bootstrap server uses rdap.afilias.net for a list of specific gTLDs and as a default fallback in domain lookup.
It seems this endpoint has been down for some time. Searches showed that Afilias was acquired and now a part of company Identity.Digital. However I couldn't find any public RDAP endpoints on their site.

On a technical side, this issue leads to timeouts for a part of domain names when querying https://rdap-bootstrap.arin.net/bootstrap/domain/ (as I believe it runs on this code), if a client follows redirects automatically.

**Comment by gdubin** [comment]
Thank you for bringing this to our attention.  The content for the file in question is actually maintained by another organization.  I'll open a ticket with them to correct the content and we'll update our repository once it's been fixed.

**Comment by gdubin** [comment]
I think this has been resolved.  If you still see the issue, please let us know.

**Comment by guzzijones** [comment]
we are still seeing this issue when querying rdap.arin.net. is there another rdap server we should use?

**Comment by guzzijones** [comment]
The specific uri we are hitting is `https://rdap.arin.net/bootstrap/domain/{0}'.format(indicator)`
